- hosts: localhost
  become: False
  gather_facts: False

  vars:
    git2play_repo: https://github.com/victorock/ansible-devops.git
    git2play_clone: yes
    git2play_update: yes
    git2play_track_submodules: yes
    git2play_version: dev
    git2play_playbook: site.yml
    git2play_skip_tags: undefined
    git2play_only_tags: undefined

  tasks:
    - name: Create temporary git2play directory
      tempfile:
        state: directory
        suffix: git2play
      register: tempdir

    - name: Git clone {{ git2play_repo }} at {{ tempdir.path }}
      git:
        repo: "{{ git2play_repo }}"
        dest: "{{ tempdir.path }}"
        clone: "{{ git2play_clone }}"
        update: "{{ git2play_update }}"
        track_submodules: "{{ git2play_track_submodules }}"
        version: "{{ git2play_version }}"

    - name: Check if ansible-galaxy is required
      stat:
        path: "{{ tempdir.path }}/roles/requirements.yml"
      register: galaxy

    - name: ansible-galaxy install roles/requirements.yml at roles/
      command: >
        ansible-galaxy install
        -r roles/requirements.yml
        -p roles
      args:
        chdir: "{{ tempdir.path }}"
      when: galaxy.stat.isreg

    - name: ansible-playbook {{ git2play_playbook }}
      command: >
        ansible-playbook {{ git2play_playbook }}
        --skip-tags={{ git2play_skip_tags }}
        --tags={{ git2play_only_tags }}
      args:
        chdir: "{{ tempdir.path }}"

    - name: Ensure {{ tempdir.path }} directory is absent
      file:
        path: "{{ tempdir.path }}"
        state: absent
