---
- hosts: localhost
  connection: local
  become: no
  gather_facts: no

  vars:
    ec2_region: "eu-central-1"
    ec2_cloud_instances: "1"
    ec2_cloud_instance_type: "t2.micro"
    ec2_cloud_instance_os: CentOS Linux 7 x86_64*
    ec2_cloud_instance_os_type: linux
    ec2_cloud_instance_boot_disk_volume_size: 60
    ec2_cloud_instance_boot_disk_delete_on_termination: yes

  tasks:
    - name: "AWS Instance"
      include_role:
        name: victorock.aws-cloud
