---
- hosts: all
  gather_facts: yes

  tasks:
    - name: "Update packages"
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - ServicePacks
        state: installed
