---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update packages
      yum:
        name: '*'
        update_cache: yes
        validate_certs: no
        security: yes
        state: latest
