- name: "Linux Traceroute (UDP)"
  hosts: all
  gather_facts: no

  vars:
    peers:
      - { host: 10.42.0.11, maxhops: 30, wait: 2, packet_size_kb: 64 }

  tasks:
    - name: "Traceroute reachability"
      shell: traceroute -Fen -w {{ udp_trace.wait }} -m {{ udp_trace.maxhops }} {{ udp_trace.host }} {{ udp_trace.packet_size_kb }}
      register: r_shell
      with_items: "{{ peers }}"
      loop_control:
        loop_var: udp_trace
        label: "{{ udp_trace.host }}"

    - name: "Output"
      debug: var=r_shell
